# Generated by Django 3.2 on 2021-04-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevent',
            name='event_broadcast_url',
            field=models.URLField(blank=True, null=True, verbose_name='event_broadcast_url'),
        ),
    ]
